package it.polimi.ingsw.model;

/**
 * All the possible update events
 */
public enum EVENT {
    CREATE_WORLD,
    CREATE_CLOUDS,
    CREATE_PLAYERS,
    CREATE_CHARACTERS,
    CHANGE_CHARACTER_S,
    CHANGE_CHARACTER_NE,
    REPLACE_CHARACTER_S,
    REPLACE_CHARACTER_NE,
    ADD_PLAYER,
    REPLACE_PLAYER,
    CHANGE_ISLAND,
    REPLACE_ISLAND,
    CHANGE_CLOUD,
    REPLACE_CLOUD,
    REPLACE_CHARACTER,
    REPLACE_PROFS,
    CHANGE_SCHOOLBOARD,
    MN_POS,
    BOARD_COINS,
    PLAYER_COINS,
    CHARACTER_COST
}
